### ISSUE TITLE
Infinite red health generation with Mom's Locket.

### ISSUE THREAD

**Issue by Jarkko-Hokkanen** [machasins/isaac_heart_mod#3]
While holding Mom's Locket, picking up a full red heart while missing half a red heart spawns a full red heart.

**Comment by machasins** [comment]
Thank you for your report. 

Unfortunately it seems like Mom's Locket continuously converts half red hearts to full red hearts, meaning that half red hearts are impossible to spawn while Mom's Locket is held.

To counter this, when Mom's Locket is held, half red hearts will not generate, and you will lose that remaining health.

It would also be possible to abuse Mom's Locket by dropping it before picking up the health (one full heart when missing half), then picking up Mom's Locket again to transform the remaining half red heart into a full red heart. I think countering this specific strategy would require too much effort on my part (ie searching the entire floor for Mom's Locket, as well as other players, and even unopened chests with Guppy's Eye might have Mom's Locket), so that will be ignored. Unless anyone has a suggestion for fixing/getting around that.

Thanks again.
